apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: rpchealth
  name: rpchealth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rpchealth
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/rpchealth-default: "true"
        io.kompose.service: rpchealth
    spec:
      containers:
        - image: darkobas/rpchealth:latest
          name: rpchealth
          ports:
            - containerPort: 9999
          resources: {}
      restartPolicy: Always
status: {}
